{{- if .Values.config }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Release.Name }}"
data:
  {{- if .Values.config.tags }}
  TAGS: {{ .Values.config.tags | b64enc }}
  {{- end }}
  {{- if not .Values.config.tags }}
  TAGS: ''
  {{- end }}
  {{- if .Values.config.token }}
  TOKEN: {{ .Values.config.token | b64enc }}
  {{- end }}
  {{- if not .Values.config.token }}
  TOKEN: ''
  {{- end }}
  {{- if not .Values.config.aws }}
  AWS_SECRET_MANAGER: {{ "false"  | b64enc }}
  {{- end }}
  {{- with .Values.config.aws }}
  AWS_SECRET_MANAGER: {{ "true" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .access_key_id | default "" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .secret_access_key |default "" | b64enc }}
  AWS_REGION: {{ .region | default "us-east-1" | b64enc }}
  {{- end }}
  {{- if .Values.config.jwk_url }}
  JWK_URL: {{ .Values.config.jwk_url | b64enc }}
  {{- end }}
  {{- if not .Values.config.jwk_url }}
  JWK_URL: ''
  {{- end }}
{{- end }}
---
{{- if .Values.env_var }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-envvar"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Release.Name }}"
data:
  {{- range $key, $val := .Values.env_var }}
  {{ $key }}: {{ printf "%v" $val | b64enc }}
  {{- end}}
{{- end }}