name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.6

      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        
      - name: Docker Login
        run: docker login -u=${{ secrets.DOCKER_LOGIN }} -p=${{ secrets.DOCKER_PASSWORD }}

      - name: Lein Deps
        run: lein deps
  
      - name: Test
        run: make test

      - name: Build Jar
        run: make build

      - name: Publish Jar
        run: make gh-upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: make docker-build
      
      - name: Publish Docker Image
        run: make docker-push
